# Generated by Django 3.2.5 on 2021-07-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('id_espaider', models.IntegerField()),
                ('phone_1', models.IntegerField()),
                ('phone_2', models.IntegerField()),
                ('phone_hot', models.IntegerField()),
                ('phone_whatsapp', models.IntegerField()),
                ('id_debtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='walls.devedor')),
            ],
        ),
    ]
